name: Windows MSVC Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # # -------------------------
      # # Setup MSVC environment
      # # -------------------------
      # - name: Setup MSVC
      #   uses: ilammy/msvc-dev-cmd@v1

      # # -------------------------
      # # Install CMake
      # # -------------------------
      # - name: Install CMake
      #   uses: lukka/get-cmake@latest

      # # -------------------------
      # # Setup vcpkg (for GMP + OpenCV)
      # # -------------------------
      # - name: Clone vcpkg
      #   run: |
      #     git clone https://github.com/microsoft/vcpkg.git ${{ github.workspace }}\vcpkg

      # - name: Bootstrap vcpkg
      #   run: |
      #     ${{ github.workspace }}\vcpkg\bootstrap-vcpkg.bat
      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: |
            C:\vcpkg\installed
            C:\vcpkg\buildtrees
            C:\vcpkg\packages
          key: vcpkg-${{ runner.os }}-opencv-gmp
      # -------------------------
      # Install dependencies
      # -------------------------
      - name: Install GMP and OpenCV
        shell: cmd
        run: |
          rem choco install opencv -y
          set VCPKG_BUILD_TYPE=release
          C:\vcpkg\vcpkg.exe install gmp:x64-windows-release
          C:\vcpkg\vcpkg.exe integrate install


      # -------------------------
      # Run your build script
      # -------------------------
      - name: Run build.bat
        shell: cmd
        run: |
          call build.bat
        continue-on-error: true

      # -------------------------
      # Upload output folder
      # -------------------------
      - name: Upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: output/
      - name: Create Release + Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: auto-release
          body: "This is an auto-release. I'm not sure if this is trustworthy or not. Just go with the latest."
          files: out.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
